# Teacher训练配置文件
# 使用UNet++作为Teacher模型的标准训练

# === 基础训练配置 ===
epochs: 25              # 增加训练轮数以提高精度
batch_size: 6           # 稍微增加batch size
lr: 0.0003              # 提高学习率加快收敛
img_size: 384           # 提高分辨率以获得更精细的分割
num_workers: 0          
num_classes: 3          

# === 数据配置 ===
split: "train"
binary: false           
val_ratio: 0.2          
monitor_interval: 10    

# === 关键：使用相同的分类方案 ===
classification_scheme: "3class_org"    

# === 标准训练模式（非蒸馏） ===
enable_distillation: false  # 关键：关闭蒸馏模式
model: "unet_plus_plus"      # 单独训练UNet++作为Teacher

# === 训练策略 ===
stage: "offline"

# === 优化器配置 ===
optimizer: "adamw"
weight_decay: 0.0001
scheduler: "cosine"

# === 数据增强 ===
augment: true
flip_prob: 0.5
rotation_degree: 20     # 增加旋转角度
# 添加更多数据增强选项

# === FOV处理 ===
apply_fov_mask: true  # 是否应用视野遮罩去除黑边

# === 监控和可视化 ===
enable_gpu_monitor: true
save_viz: true
viz_samples: 6

# === 保存策略 ===
save_interval: 3        # 更频繁保存以监控训练进度
val_interval: 1
save_best_only: true

# === 调试配置 ===
debug: false
early_stopping: true
patience: 8             # 增加patience以避免过早停止
