# Teacher训练配置文件
# 使用UNet++作为Teacher模型的标准训练

# === 基础训练配置 ===
epochs: 12              # 测试用快速训练
batch_size: 4           
lr: 0.0001              
img_size: 256           
num_workers: 0          
num_classes: 3          

# === 数据配置 ===
split: "train"
binary: false           
val_ratio: 0.2          
monitor_interval: 10    

# === 关键：使用相同的分类方案 ===
classification_scheme: "3class_org"    

# === 标准训练模式（非蒸馏） ===
enable_distillation: false  # 关键：关闭蒸馏模式
model: "unet_plus_plus"      # 单独训练UNet++作为Teacher

# === 训练策略 ===
stage: "offline"

# === 优化器配置 ===
optimizer: "adamw"
weight_decay: 0.0001
scheduler: "cosine"

# === 数据增强 ===
augment: true
flip_prob: 0.5
rotation_degree: 10

# === 监控和可视化 ===
enable_gpu_monitor: true
save_viz: true
viz_samples: 6

# === 保存策略 ===
save_interval: 5
val_interval: 1
save_best_only: true

# === 调试配置 ===
debug: false
early_stopping: true
patience: 5
